## Numpy的核心array对象以及创建array的方法

#### array对象的背景：
* Numpy的核心数据结构，就叫做array就是数组，array对象可以是一维数组，也可以是多维数组；
* Python的List也可以实现相同的功能，但是array比List的优点在于性能好、包含数组元数据信息、大量的便捷函数；
* Numpy成为事实上的Scipy、Pandas、Scikit-Learn、Tensorflow、PaddlePaddle等框架的“通用底层语言”
* Numpy的array和Python的List的一个区别，是它元素必须都是同一种数据类型，比如都是数字int类型，这也是Numpy高性能的一个原因；

#### array本身的属性
* shape：返回一个元组，表示array的维度
* ndim：一个数字，表示array的维度的数目
* size：一个数字，表示array中所有数据元素的数目
* dtype：array中元素的数据类型

#### 创建array的方法
* 从Python的列表List和嵌套列表创建array
* 使用预定函数arange、ones/ones_like、zeros/zeros_like、empty/empty_like、full/full_like、eye等函数创建
* 生成随机数的np.random模块构建

#### array本身支持的大量操作和函数
* 直接逐元素的加减乘除等算数操作
* 更好用的面向多维的数组索引
* 求sum/mean等聚合函数
* 线性代数函数，比如求解逆矩阵、求解方程组

### 1. 使用Python的List和嵌套List创建一维的array和二维的array

In [1]:
import numpy as np

In [2]:
# 创建一个一维数组，也就是Python的单元素List
x = np.array([1,2,3,4,5,6,7,8])

In [3]:
x

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
# 创建一个二维数组，也就是Python的嵌套List
X = np.array(
    [
        [1,2,3,4],
        [5,6,7,8]
    ]
)

In [5]:
X

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### 2. 探索数组array的属性

In [6]:
x.shape

(8,)

In [7]:
X.shape

(2, 4)

In [8]:
x.ndim

1

In [9]:
X.ndim

2

In [10]:
x.size

8

In [11]:
X.size

8

In [12]:
x.dtype

dtype('int32')

In [13]:
X.dtype

dtype('int32')

### 3. 创建array的便捷函数

#### 使用arange创建数字序列

arange([start,] stop[, step,], dtype=None)

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(2, 10, 2)

array([2, 4, 6, 8])

#### 使用ones创建全是1的数组

np.ones(shape, dtype=None, order='C')

shape : int or tuple of ints
Shape of the new array, e.g., ``(2, 3)`` or ``2``.

In [16]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

#### 使用ones_like创建形状相同的数组

ones_like(a, dtype=float, order='C')

In [18]:
np.ones_like(x)

array([1, 1, 1, 1, 1, 1, 1, 1])

In [19]:
np.ones_like(X)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

#### 使用zeros创建全是0的数组
np.zeros(shape, dtype=None, order='C')

In [20]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### 使用zeros_like创建形状相同的数组¶
np.zeros_like(a, dtype=None)

In [22]:
np.zeros_like(x)

array([0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
np.zeros_like(X)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

#### 使用empty创建全是0的数组
empty(shape, dtype=float, order='C')   
注意：数据是未初始化的，里面的值可能是随机值不要用

In [24]:
np.empty(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.empty((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### 使用empty_like创建形状相同的数组¶
empty_like(prototype, dtype=None)

In [26]:
np.empty_like(x)

array([0, 0, 0, 0, 0, 0, 0, 0])

In [27]:
np.empty_like(X)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

#### 使用full创建指定值的数组
np.full(shape, fill_value, dtype=None, order='C')

In [28]:
np.full(10, 666)

array([666, 666, 666, 666, 666, 666, 666, 666, 666, 666])

In [29]:
np.full((2,4), 333)

array([[333, 333, 333, 333],
       [333, 333, 333, 333]])

#### 使用full_like创建形状相同的数组¶
np.full_like(a, fill_value, dtype=None)

In [30]:
np.full_like(x, 666)

array([666, 666, 666, 666, 666, 666, 666, 666])

In [31]:
np.full_like(X, 666)

array([[666, 666, 666, 666],
       [666, 666, 666, 666]])

#### 使用random模块生成随机数的数组

randn(d0, d1, ..., dn)

In [32]:
np.random.randn()

1.1106391311802373

In [33]:
np.random.randn(3)

array([0.30501947, 1.5935427 , 2.19706265])

In [34]:
np.random.randn(3, 2)

array([[ 1.91805826, -0.67076574],
       [-0.66382633, -0.32008601],
       [-0.54977281,  0.84384816]])

In [35]:
np.random.randn(3, 2, 4)

array([[[ 0.7419018 ,  0.22271303, -0.54512429,  0.48523073],
        [ 0.01613781,  0.74694664, -0.56695606,  0.20488094]],

       [[-0.08818788,  1.09166684,  0.38169304, -0.00319349],
        [ 1.01200773, -0.57815559,  0.63535043,  1.41703628]],

       [[-0.76849101, -1.50895899,  0.38588873,  0.97316552],
        [-0.60922509,  0.62118775, -0.70502845, -0.61426203]]])

### 4. array本身支持的大量操作和函数

这些操作如果用Python实现需要写很多for循环，用numpy数组很容易

In [36]:
A = np.arange(10).reshape(2,5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [37]:
A.shape

(2, 5)

In [38]:
A+1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [39]:
A*3

array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27]])

In [40]:
np.sin(A)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849]])

In [41]:
np.exp(A)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
        8.10308393e+03]])

In [42]:
B = np.random.randn(2,5)
B

array([[ 0.39961078, -0.2358424 ,  0.22736848, -0.22654917,  0.02110567],
       [ 1.20000351, -0.18548543, -1.33659976,  1.48071382, -1.73020108]])

In [43]:
A+B

array([[0.39961078, 0.7641576 , 2.22736848, 2.77345083, 4.02110567],
       [6.20000351, 5.81451457, 5.66340024, 9.48071382, 7.26979892]])

In [44]:
A-B

array([[-0.39961078,  1.2358424 ,  1.77263152,  3.22654917,  3.97889433],
       [ 3.79999649,  6.18548543,  8.33659976,  6.51928618, 10.73020108]])