## Numpy非常有用的数组合并操作

背景：在给机器学习准备数据的过程中，经常需要进行不同来源的数据合并的操作。

以下操作均可以实现数组合并：
* np.concatenate(array_list, axis=0/1）：沿着指定axis进行数组的合并
* np.vstack或者np.row_stack(array_list)：垂直vertically、按行row wise进行数据合并
* np.hstack或者np.column_stack(array_list)：水平horizontally、按列column wise进行数据合并

In [1]:
import numpy as np

### 1. 怎样按行合并数据

实例：已经有了一组样本数据，新来了一条或者一组样本数据，怎样合并？

In [27]:
# 已经有的样本数据
X = np.array(
    [
        [11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]
    ]
)
X

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

### 1. np.concatenate

In [8]:
a = np.arange(6).reshape(2,3)
b = np.random.randint(10,20,size=(2,3))

In [9]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [10]:
b

array([[18, 18, 18],
       [12, 10, 19]])

In [11]:
np.concatenate([a,b])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [18, 18, 18],
       [12, 10, 19]])

In [12]:
np.concatenate([a,b], axis=1)

array([[ 0,  1,  2, 18, 18, 18],
       [ 3,  4,  5, 12, 10, 19]])

### 2. np.vstack或者np.row_stack

In [13]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
b

array([[18, 18, 18],
       [12, 10, 19]])

#### np.vstack

In [15]:
np.vstack([a,b])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [18, 18, 18],
       [12, 10, 19]])

#### np.row_stack

In [20]:
np.row_stack([a,b])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [18, 18, 18],
       [12, 10, 19]])

### 3. np.hstack或者np.column_stack

In [16]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [17]:
b

array([[18, 18, 18],
       [12, 10, 19]])

#### np.hstack

In [19]:
np.hstack([a,b])

array([[ 0,  1,  2, 18, 18, 18],
       [ 3,  4,  5, 12, 10, 19]])

#### np.column_stack

In [21]:
np.column_stack([a,b])

array([[ 0,  1,  2, 18, 18, 18],
       [ 3,  4,  5, 12, 10, 19]])

In [23]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.stack((a, b)).shape

(2, 3)