## Numpy中数组的乘法

按照两个相乘数组A和B的维度不同，分为以下乘法：
1. 数字与一维/二维数组相乘；
2. 一维数组与一维数组相乘；
3. 二维数组与一维数组相乘；
4. 二维数组与二维数组相乘；

**numpy有以下乘法函数：**  
1. *符号或者np.multiply：逐元素乘法，对应位置的元素相乘，要求shape相同
2. @符号或者np.matmul：矩阵乘法，形状要求满足(n,k),(k,m)->(n,m)
3. np.dot：点积乘法

**解释：点积，也叫内积，也叫数量积**  
两个向量a = [a1, a2,…, an]和b = [b1, b2,…, bn]的点积定义为：   
a·b=a1b1+a2b2+……+anbn。

In [1]:
import numpy as np

### 1. 数字与一维数组/二维数组相乘

#### 一维数组

In [2]:
A = np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# *意思是逐元素乘法
A * 0.5

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

#### 二维数组

In [4]:
B = np.arange(12).reshape(3, 4)
B

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
B * 0.5

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

### 2. 一维数组与一维数组相乘

In [6]:
A = np.arange(1, 11)
A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
B = np.arange(1, 11) * 0.1
B

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

#### 逐元素乘法

In [8]:
np.multiply(A, B)

array([ 0.1,  0.4,  0.9,  1.6,  2.5,  3.6,  4.9,  6.4,  8.1, 10. ])

In [9]:
A * B

array([ 0.1,  0.4,  0.9,  1.6,  2.5,  3.6,  4.9,  6.4,  8.1, 10. ])

#### 点积/内积/数量积

In [11]:
A@B

38.5

In [12]:
np.matmul(A, B)

38.5

In [10]:
np.dot(A, B)

38.5

In [13]:
# 以上三个，相当于
np.sum(A*B)

38.5

### 3. 二维数组和一维数组相乘

In [14]:
A = np.arange(1, 21).reshape(5, 4)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [15]:
B = np.arange(1, 5) * 0.1
B

array([0.1, 0.2, 0.3, 0.4])

#### 逐元素乘法

In [16]:
A*B

array([[0.1, 0.4, 0.9, 1.6],
       [0.5, 1.2, 2.1, 3.2],
       [0.9, 2. , 3.3, 4.8],
       [1.3, 2.8, 4.5, 6.4],
       [1.7, 3.6, 5.7, 8. ]])

In [17]:
np.multiply(A, B)

array([[0.1, 0.4, 0.9, 1.6],
       [0.5, 1.2, 2.1, 3.2],
       [0.9, 2. , 3.3, 4.8],
       [1.3, 2.8, 4.5, 6.4],
       [1.7, 3.6, 5.7, 8. ]])

#### 矩阵乘法

In [18]:
A@B

array([ 3.,  7., 11., 15., 19.])

In [19]:
np.matmul(A, B)

array([ 3.,  7., 11., 15., 19.])

In [20]:
np.dot(A, B)

array([ 3.,  7., 11., 15., 19.])

### 4. A和B都是二维数组，实现矩阵乘法

In [21]:
A = np.arange(12).reshape(3, 4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
B = np.arange(20).reshape(4, 5)
B

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [23]:
A@B

array([[ 70,  76,  82,  88,  94],
       [190, 212, 234, 256, 278],
       [310, 348, 386, 424, 462]])

In [24]:
np.matmul(A, B)

array([[ 70,  76,  82,  88,  94],
       [190, 212, 234, 256, 278],
       [310, 348, 386, 424, 462]])

In [25]:
np.dot(A, B)

array([[ 70,  76,  82,  88,  94],
       [190, 212, 234, 256, 278],
       [310, 348, 386, 424, 462]])