## Numpy求解线性方程组

对于Ax=b，已知A和b，怎么算出x?

### 1. 引入包

In [1]:
import numpy as np

### 2. 求解

In [2]:
A = np.array(
    [
        [1, -2, 1],
        [0, 2, -8],
        [-4, 5, 9]
    ]
)
A

array([[ 1, -2,  1],
       [ 0,  2, -8],
       [-4,  5,  9]])

In [3]:
b = np.array([0, 8, -9])
b

array([ 0,  8, -9])

In [4]:
# 调用solve方法直接求解
x = np.linalg.solve(A, b)
x

array([29., 16.,  3.])

### 验证

In [5]:
# 验证单个方程
A[1].dot(x)

8.0

In [6]:
# 验证整个矩阵计算
A.dot(x) == b

array([ True,  True,  True])