## Numpy实现SVD矩阵分解

### 1. 引入包

In [1]:
import numpy as np

### 2. 实现矩阵分解

In [2]:
A = np.random.randint(1, 10, (8, 4))

In [3]:
A

array([[6, 5, 1, 5],
       [1, 7, 9, 7],
       [7, 2, 4, 2],
       [6, 4, 3, 5],
       [2, 8, 8, 6],
       [5, 2, 8, 6],
       [7, 8, 2, 3],
       [1, 3, 6, 9]])

In [4]:
# 实现矩阵分解
U, S, V = np.linalg.svd(A, full_matrices=False)

In [5]:
U.shape, S.shape, V.shape

((8, 4), (4,), (4, 4))

In [6]:
U

array([[-0.28611227, -0.38768744, -0.07088588, -0.47757145],
       [-0.44374671,  0.40390585, -0.25458601,  0.20383531],
       [-0.24657791, -0.34884357,  0.43054458,  0.4062272 ],
       [-0.30673084, -0.27495123,  0.14797683, -0.2218886 ],
       [-0.43671345,  0.23339125, -0.39431663,  0.27599841],
       [-0.37257929,  0.10313032,  0.59362412,  0.23542645],
       [-0.33314069, -0.52514475, -0.41727103,  0.07285924],
       [-0.35472167,  0.38520663,  0.20225001, -0.61580222]])

In [7]:
# 因为是对角矩阵，这里进行了简写
S

array([28.44730142, 10.24874824,  6.39012419,  4.56952014])

In [8]:
np.diag(S)

array([[28.44730142,  0.        ,  0.        ,  0.        ],
       [ 0.        , 10.24874824,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  6.39012419,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  4.56952014]])

In [9]:
V

array([[-0.39194862, -0.50004828, -0.54329548, -0.54877866],
       [-0.81202147, -0.18350883,  0.48594814,  0.26608277],
       [ 0.41980592, -0.84227439,  0.27814277,  0.19228481],
       [ 0.10373231,  0.08276523,  0.62555658, -0.76880979]])

### 3. 从分量还原矩阵

In [10]:
U @ np.diag(S) @ V

array([[6., 5., 1., 5.],
       [1., 7., 9., 7.],
       [7., 2., 4., 2.],
       [6., 4., 3., 5.],
       [2., 8., 8., 6.],
       [5., 2., 8., 6.],
       [7., 8., 2., 3.],
       [1., 3., 6., 9.]])