## Numpy计算逆矩阵求解线性方程组

对于这样的线性方程组：
* x + y + z = 6
* 2y + 5z = -4
* 2x + 5y - z = 27

可以表示成矩阵的形式：
<img style="margin-left:0px" src="./other_files/numpy-array-inv.jpg" />

用公式可以表示为：Ax=b，其中A是矩阵，x和b都是列向量

***逆矩阵（inverse matrix）的定义：***  
设A是数域上的一个n阶矩阵，若存在另一个n阶矩阵B，使得： AB=BA=E ，则我们称B是A的逆矩阵，而A则被称为可逆矩阵。注：E为单位矩阵。

***使用逆矩阵求解线性方程组的方法：***  
两边都乘以$A^{-1}$，变成$A^{-1}$Ax=$A^{-1}$b，因为任何矩阵乘以单位矩阵都是自身，所以x=$A^{-1}$b

In [1]:
import numpy as np

### 1. 求解逆矩阵

In [2]:
A = np.array([
    [1,1,1],
    [0,2,5],
    [2,5,-1]
])
A

array([[ 1,  1,  1],
       [ 0,  2,  5],
       [ 2,  5, -1]])

In [3]:
# B为A的逆矩阵
B = np.linalg.inv(A)
B

array([[ 1.28571429, -0.28571429, -0.14285714],
       [-0.47619048,  0.14285714,  0.23809524],
       [ 0.19047619,  0.14285714, -0.0952381 ]])

### 2. 验证矩阵和逆矩阵的乘积是单位矩阵

In [4]:
A@B

array([[ 1.00000000e+00, -2.77555756e-17,  2.77555756e-17],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [-2.22044605e-16,  5.55111512e-17,  1.00000000e+00]])

In [5]:
np.matmul(A, B)

array([[ 1.00000000e+00, -2.77555756e-17,  2.77555756e-17],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [-2.22044605e-16,  5.55111512e-17,  1.00000000e+00]])

### 3. 验证线性方程组

In [6]:
# 构造Ax=b中的b
b = np.array([6, -4, 27])

In [7]:
# 使用逆矩阵求解x
x = B@b

In [8]:
x

array([ 5.,  3., -2.])

In [9]:
# 验证A@x = b
A@x

array([ 6., -4., 27.])