## Numpy怎样将数组读写到文件

本文档介绍的是Numpy以自己内建二进制的方式，将数组写出到文件，以及从文件加载数组；

如果是文本、表格类数据，一般使用pandas这个类库做加载和处理，不用numpy

几个方法：
1. np.load(filename)：从.npy或者.npz文件中加载numpy数组  
如果文件后缀是.npy返回单个数组，如果文件后缀是.npz返回多个数组的字典
2. np.save(filename, arr)：将单个numpy数组保存到.npy文件中
3. np.savez(filename, arra=arra, arrb=arrb)：将多个numpy数组保存到.npz未压缩的文件格式中
4. np.savez_compressed(filename, arra=arra, arrb=arrb)：将多个numpy数组保存到.npz压缩的文件格式中

.npy和.npz都是二进制格式文件，用纯文本编辑器打开都是乱码

In [1]:
import numpy as np

### 1. 使用np.save和np.load保存和加载单个数组

In [2]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
# 把单个数组保存到.npy文件
np.save("arr_a.npy", a)

In [4]:
# 从.npy文件加载单个数组
b = np.load("arr_a.npy")
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### 2. 使用np.savez和np.load保存和加载多个数组

In [5]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
b = np.random.rand(2, 3)
b

array([[0.06355473, 0.69576567, 0.17754786],
       [0.28343315, 0.29994149, 0.76737219]])

In [7]:
# 保存多个数组到一个文件
np.savez("arr_ab.npz", a=a, b=b)

In [8]:
# 从.npz读取多个数组，返回一个字典形式
data = np.load("arr_ab.npz")
data

In [9]:
data["a"]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
data["b"]

array([[0.06355473, 0.69576567, 0.17754786],
       [0.28343315, 0.29994149, 0.76737219]])

### 3. 使用np.savez_compressed和np.load保存和加载多个数组到压缩格式文件

In [11]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
b

array([[0.06355473, 0.69576567, 0.17754786],
       [0.28343315, 0.29994149, 0.76737219]])

In [13]:
# 保存多个数组到压缩文件
np.savez_compressed("arr_ab_compressed.npz", a=a, b=b)

In [14]:
# 同样用np.load加载.npz文件
data = np.load("arr_ab_compressed.npz")

In [15]:
data["a"]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
data["b"]

array([[0.06355473, 0.69576567, 0.17754786],
       [0.28343315, 0.29994149, 0.76737219]])